# -*- coding: utf-8 -*-
"""
scorers_data.py
Sistema de goleadores y estadísticas de jugadores para FMMJ WORLD CUP UNITED 26.
"""

# Plantilla de jugadores por selección (simulada)
TEAM_SQUADS = {
    "MEX": [
        "G. Mora",
        "A. Vega",
        "L. Romo",
        "C. Montes",
        "A. Gonz\u00e1lez",
        "I. Reyes",
        "R. Rangel",
        "G. Mart\u00ednez",
        "B. Guti\u00e9rrez",
        "L. Ch\u00e1vez",
        "C. Acevedo",
        "G. Ochoa",
        "R. Alvarado",
        "E. Lira",
        "J. Gallardo",
        "S. Gim\u00e9nez",
        "R. Jim\u00e9nez",
        "C. Huerta",
        "O. Vargas",
        "O. Pineda",
        "E. \u00c1lvarez",
        "J. S\u00e1nchez",
        "Fidalgo",
        "M. Ch\u00e1vez",
        "J. V\u00e1squez",
        "J. Qui\u00f1ones"
    ],
    "KOR": [
        "Kim Seung Gyu",
        "Lee Han Beom",
        "Kim Min Jae",
        "Lee Gi Hyuk",
        "Seol Young Woo",
        "Paik Seung Ho",
        "Hwang In Beom",
        "J. Castrop",
        "Lee Kang In",
        "Lee Jae Sung",
        "Son Heung Min",
        "Hwang Hee Chan",
        "Oh Hyeon Gyu",
        "Yang Hyun Jun",
        "Park Jin Seob",
        "Kim Moon Hwan",
        "Lee Tae Seok",
        "Jo Hyeon Woo",
        "Kim Jin Gyu",
        "Eom Ji Sung",
        "Lee Dong Gyeong",
        "Bae Jun Ho",
        "Cho Wi Je",
        "Song Bum Keun",
        "Kim Tae Hyeon",
        "Cho Gue Sung"
    ],
    "UKR": [
        "A. Trubin",
        "Y. Konoplia",
        "I. Zabarnyi",
        "M. Matviienko",
        "V. Mykolenko",
        "A. Bondarenko",
        "V. Brazhko",
        "V. Tsygankov",
        "G. Sudakov",
        "M. Shaparenko",
        "A. Dovbyk",
        "R. Yaremchuk",
        "R. Malinovskyi",
        "O. Hutsuliak",
        "O. Nazarenko",
        "I. Kaliuzhnyi",
        "V. Bondar",
        "G. Bushchan",
        "V. Vanat",
        "B. Mykhailichenko",
        "Y. Yarmoliuk",
        "D. Riznyk",
        "O. Karavaiev",
        "N. Voloshyn",
        "V. Veleten",
        "O. Svatok"
    ],
    "NOR": [
        "\u00d8. Nyland",
        "J. Ryerson",
        "K. Ajer",
        "T. Heggem",
        "D. Wolfe",
        "M. \u00d8degaard",
        "S. Berge",
        "P. Berg",
        "A. S\u00f8rloth",
        "E. Haaland",
        "A. Nusa",
        "F. Aursnes",
        "O. Bobb",
        "T. Aasgaard",
        "F. Bj\u00f8rkan",
        "L. \u00d8stig\u00e5rd",
        "M. Pedersen",
        "E. Selvik",
        "A. Schjelderup",
        "J. Strand Larsen",
        "S. Tangvik",
        "K. Thorstvedt",
        "J. Hauge",
        "H. Falchener",
        "S. Lang\u00e5s",
        "M. Thorsby"
    ],
    "CAN": [
        "M. Cr\u00e9peau",
        "A. Johnston",
        "M. Bombito",
        "L. De Fougerolles",
        "R. Laryea",
        "T. Buchanan",
        "N. Sigur",
        "Stephen Eust\u00e1quio",
        "A. Ahmed",
        "J. David",
        "T. Oluwaseyi",
        "L. Millar",
        "J. Osorio",
        "N. Saliba",
        "A. Davies",
        "D. Cornelius",
        "A. Jones",
        "D. St. Clair",
        "P. David",
        "C. Larin",
        "O. Goodman",
        "J. Waterman",
        "I. Kon\u00e9",
        "J. Nelson",
        "M. Choini\u00e8re",
        "J. Shaffelburg"
    ],
    "SUI": [
        "G. Kobel",
        "S. Widmer",
        "N. Elvedi",
        "M. Akanji",
        "R. Rodr\u00edguez",
        "R. Freuler",
        "G. Xhaka",
        "D. Ndoye",
        "R. Vargas",
        "J. Manzambi",
        "B. Embolo",
        "N. Okafor",
        "D. Zakaria",
        "A. Jashari",
        "F. Rieder",
        "M. Muheim",
        "A. Amenda",
        "Y. Mvogo",
        "M. Aebischer",
        "Z. Amdouni",
        "C. Fassnacht",
        "D. Sow",
        "E. C\u00f6mert",
        "M. Keller",
        "L. Jaquez",
        "C. Itten"
    ],
    "ITA": [
        "G. Donnarumma",
        "M. Politano",
        "G. Mancini",
        "A. Bastoni",
        "R. Calafiori",
        "F. Dimarco",
        "M. Locatelli",
        "N. Barella",
        "S. Tonali",
        "M. Kean",
        "M. Retegui",
        "G. Raspadori",
        "B. Cristante",
        "D. Frattesi",
        "L. Spinazzola",
        "F. Gatti",
        "M. Palestra",
        "M. Carnesecchi",
        "A. Buongiorno",
        "F. Esposito",
        "A. Meret",
        "A. Cambiaso",
        "N. Pisilli",
        "E. Caprile",
        "G. Scalvini",
        "G. Scamacca"
    ],
    "ARG": [
        "E. Mart\u00ednez",
        "G. Montiel",
        "C. Romero",
        "L. Mart\u00ednez",
        "N. Tagliafico",
        "R. De Paul",
        "E. Fern\u00e1ndez",
        "A. Mac Allister",
        "N. Gonzalez",
        "L. Messi",
        "J. Alvarez",
        "L. Mart\u00ednez",
        "Nico Paz",
        "L. Paredes",
        "T. Almada",
        "N. Otamendi",
        "F. Medina",
        "G. Rulli",
        "Giuliano",
        "G. Lo Celso",
        "N. Molina",
        "M. Senesi",
        "J. Musso",
        "E. Palacios",
        "J. L\u00f3pez",
        "V. Barco"
    ],
    "MAR": [
        "Y. Bounou",
        "A. Hakimi",
        "I. Diop",
        "R. Halhal",
        "N. Mazraoui",
        "A. Bouaddi",
        "N. El Aynaoui",
        "Brahim",
        "B. El Khannouss",
        "A. Ounahi",
        "I. Saibari",
        "S. Rahimi",
        "C. Talbi",
        "S. Amrabat",
        "S. El Mourabet",
        "Z. El Ouahdi",
        "M. Saadane",
        "M. El Kajoui",
        "A. El Kaabi",
        "A. Amaimouni",
        "G. Yassine",
        "A. Sba\u00ef",
        "A. Salah-Eddine",
        "C. Riad",
        "Y. Belammari",
        "A. Tagnaouti"
    ],
    "SCO": [
        "A. Gunn",
        "N. Patterson",
        "G. Hanley",
        "J. Hendry",
        "A. Robertson",
        "L. Ferguson",
        "R. Christie",
        "B. Gannon-Doak",
        "J. McGinn",
        "S. McTominay",
        "C. Adams",
        "L. Shankland",
        "K. McLean",
        "K. Tierney",
        "S. McKenna",
        "A. Hickey",
        "A. Ralston",
        "L. Kelly",
        "L. Dykes",
        "G. Hirst",
        "J. Souttar",
        "T. Fletcher",
        "F. Curtis",
        "D. Hyam",
        "R. Stewart"
    ],
    "POR": [
        "Diogo Costa",
        "Jo\u00e3o Cancelo",
        "R\u00faben Dias",
        "Renato Veiga",
        "Nuno Mendes",
        "Jo\u00e3o Neves",
        "Vitinha",
        "Pedro Neto",
        "Rafael Le\u00e3o",
        "Bruno Fernandes",
        "Cristiano Ronaldo",
        "Gon\u00e7alo Ramos",
        "Guedes",
        "R\u00faben Neves",
        "Bernardo Silva",
        "Gon\u00e7alo In\u00e1cio",
        "Diogo Dalot",
        "Rui Silva",
        "Jo\u00e3o F\u00e9lix",
        "Sam\u00fa Costa",
        "Trinc\u00e3o",
        "Tom\u00e1s Ara\u00fajo",
        "Matheus Nunes",
        "Francisco Concei\u00e7\u00e3o",
        "N\u00e9lson Semedo",
        "Jos\u00e9 S\u00e1"
    ]
}

def initialize_scorers_state():
    """Inicializa el estado de goleadores."""
    return {
        "scorers": []  # Lista de goles: [{"match_id": int, "team": str, "player": str, "minute": int}, ...]
    }

def add_goal(scorers_state, match_id, team, player, minute):
    """Añade un gol al registro."""
    scorers_state["scorers"].append({
        "match_id": match_id,
        "team": team,
        "player": player,
        "minute": minute
    })
    return scorers_state

def get_top_scorers(scorers_state):
    """Retorna los máximos goleadores ordenados por cantidad de goles."""
    scorer_stats = {}
    for goal in scorers_state["scorers"]:
        player = goal["player"]
        team = goal["team"]
        if player not in scorer_stats:
            scorer_stats[player] = {"team": team, "goals": 0}
        scorer_stats[player]["goals"] += 1
    
    sorted_scorers = sorted(scorer_stats.items(), key=lambda x: x[1]["goals"], reverse=True)
    return sorted_scorers
