# -*- coding: utf-8 -*-
"""
scorers_data.py
Sistema de goleadores y estadísticas de jugadores para FMMJ WORLD CUP UNITED 26.
"""

# Plantilla de jugadores por selección (simulada)
TEAM_SQUADS = {
    "MEX": [
        "G. Mora",
        "A. Vega",
        "L. Romo",
        "C. Montes",
        "A. González",
        "I. Reyes",
        "R. Rangel",
        "G. Martínez",
        "B. Gutiérrez",
        "L. Chávez",
        "C. Acevedo",
        "G. Ochoa",
        "R. Alvarado",
        "E. Lira",
        "J. Gallardo",
        "S. Giménez",
        "R. Jiménez",
        "C. Huerta",
        "O. Vargas",
        "O. Pineda",
        "E. Álvarez",
        "J. Sánchez",
        "Fidalgo",
        "M. Chávez",
        "J. Vásquez",
        "J. Quiñones"
    ],
    "KOR": [
        "Kim Seung Gyu",
        "Lee Han Beom",
        "Kim Min Jae",
        "Lee Gi Hyuk",
        "Seol Young Woo",
        "Paik Seung Ho",
        "Hwang In Beom",
        "J. Castrop",
        "Lee Kang In",
        "Lee Jae Sung",
        "Son Heung Min",
        "Hwang Hee Chan",
        "Oh Hyeon Gyu",
        "Yang Hyun Jun",
        "Park Jin Seob",
        "Kim Moon Hwan",
        "Lee Tae Seok",
        "Jo Hyeon Woo",
        "Kim Jin Gyu",
        "Eom Ji Sung",
        "Lee Dong Gyeong",
        "Bae Jun Ho",
        "Cho Wi Je",
        "Song Bum Keun",
        "Kim Tae Hyeon",
        "Cho Gue Sung"
    ],
    "UKR": [
        "A. Trubin",
        "Y. Konoplia",
        "I. Zabarnyi",
        "M. Matviienko",
        "V. Mykolenko",
        "A. Bondarenko",
        "V. Brazhko",
        "V. Tsygankov",
        "G. Sudakov",
        "M. Shaparenko",
        "A. Dovbyk",
        "R. Yaremchuk",
        "R. Malinovskyi",
        "O. Hutsuliak",
        "O. Nazarenko",
        "I. Kaliuzhnyi",
        "V. Bondar",
        "G. Bushchan",
        "V. Vanat",
        "B. Mykhailichenko",
        "Y. Yarmoliuk",
        "D. Riznyk",
        "O. Karavaiev",
        "N. Voloshyn",
        "V. Veleten",
        "O. Svatok"
    ],
    "NOR": [
        "Ø. Nyland",
        "J. Ryerson",
        "K. Ajer",
        "T. Heggem",
        "D. Wolfe",
        "M. Ødegaard",
        "S. Berge",
        "P. Berg",
        "A. Sørloth",
        "E. Haaland",
        "A. Nusa",
        "F. Aursnes",
        "O. Bobb",
        "T. Aasgaard",
        "F. Bjørkan",
        "L. Østigård",
        "M. Pedersen",
        "E. Selvik",
        "A. Schjelderup",
        "J. Strand Larsen",
        "S. Tangvik",
        "K. Thorstvedt",
        "J. Hauge",
        "H. Falchener",
        "S. Langås",
        "M. Thorsby"
    ],
    "CAN": [
        "M. Crépeau",
        "A. Johnston",
        "M. Bombito",
        "L. De Fougerolles",
        "R. Laryea",
        "T. Buchanan",
        "N. Sigur",
        "Stephen Eustáquio",
        "A. Ahmed",
        "J. David",
        "T. Oluwaseyi",
        "L. Millar",
        "J. Osorio",
        "N. Saliba",
        "A. Davies",
        "D. Cornelius",
        "A. Jones",
        "D. St. Clair",
        "P. David",
        "C. Larin",
        "O. Goodman",
        "J. Waterman",
        "I. Koné",
        "J. Nelson",
        "M. Choinière",
        "J. Shaffelburg"
    ],
    "SUI": [
        "G. Kobel",
        "S. Widmer",
        "N. Elvedi",
        "M. Akanji",
        "R. Rodríguez",
        "R. Freuler",
        "G. Xhaka",
        "D. Ndoye",
        "R. Vargas",
        "J. Manzambi",
        "B. Embolo",
        "N. Okafor",
        "D. Zakaria",
        "A. Jashari",
        "F. Rieder",
        "M. Muheim",
        "A. Amenda",
        "Y. Mvogo",
        "M. Aebischer",
        "Z. Amdouni",
        "C. Fassnacht",
        "D. Sow",
        "E. Cömert",
        "M. Keller",
        "L. Jaquez",
        "C. Itten"
    ],
    "ITA": [
        "G. Donnarumma",
        "M. Politano",
        "G. Mancini",
        "A. Bastoni",
        "R. Calafiori",
        "F. Dimarco",
        "M. Locatelli",
        "N. Barella",
        "S. Tonali",
        "M. Kean",
        "M. Retegui",
        "G. Raspadori",
        "B. Cristante",
        "D. Frattesi",
        "L. Spinazzola",
        "F. Gatti",
        "M. Palestra",
        "M. Carnesecchi",
        "A. Buongiorno",
        "F. Esposito",
        "A. Meret",
        "A. Cambiaso",
        "N. Pisilli",
        "E. Caprile",
        "G. Scalvini",
        "G. Scamacca"
    ],
    "ARG": [
        "E. Martínez",
        "G. Montiel",
        "C. Romero",
        "L. Martínez",
        "N. Tagliafico",
        "R. De Paul",
        "E. Fernández",
        "A. Mac Allister",
        "N. Gonzalez",
        "L. Messi",
        "J. Alvarez",
        "L. Martínez",
        "Nico Paz",
        "L. Paredes",
        "T. Almada",
        "N. Otamendi",
        "F. Medina",
        "G. Rulli",
        "Giuliano",
        "G. Lo Celso",
        "N. Molina",
        "M. Senesi",
        "J. Musso",
        "E. Palacios",
        "J. López",
        "V. Barco"
    ],
    "BRA": [
        "Alisson",
        "Danilo",
        "Marquinhos",
        "Gabriel",
        "Douglas Santos",
        "Casemiro",
        "Bruno Guimarães",
        "Gabriel Martinelli",
        "Rayan",
        "Matheus Cunha",
        "Vini Jr.",
        "Endrick",
        "Neymar Jr",
        "Fabinho",
        "Danilo Santos",
        "Bremer",
        "Ibañez",
        "Ederson",
        "Igor Thiago",
        "Éderson",
        "Alex Sandro",
        "Luiz Henrique",
        "Léo Pereira",
        "Weverton",
        "Lucas Paquetá",
        "Raphinha"
    ],
    "MAR": [
        "Y. Bounou",
        "A. Hakimi",
        "I. Diop",
        "R. Halhal",
        "N. Mazraoui",
        "A. Bouaddi",
        "N. El Aynaoui",
        "Brahim",
        "B. El Khannouss",
        "A. Ounahi",
        "I. Saibari",
        "S. Rahimi",
        "C. Talbi",
        "S. Amrabat",
        "S. El Mourabet",
        "Z. El Ouahdi",
        "M. Saadane",
        "M. El Kajoui",
        "A. El Kaabi",
        "A. Amaimouni",
        "G. Yassine",
        "A. Sbaï",
        "A. Salah-Eddine",
        "C. Riad",
        "Y. Belammari",
        "A. Tagnaouti"
    ],
    "SCO": [
        "A. Gunn",
        "N. Patterson",
        "G. Hanley",
        "J. Hendry",
        "A. Robertson",
        "L. Ferguson",
        "R. Christie",
        "B. Gannon-Doak",
        "J. McGinn",
        "S. McTominay",
        "C. Adams",
        "L. Shankland",
        "K. McLean",
        "K. Tierney",
        "S. McKenna",
        "A. Hickey",
        "A. Ralston",
        "L. Kelly",
        "L. Dykes",
        "G. Hirst",
        "J. Souttar",
        "T. Fletcher",
        "F. Curtis",
        "D. Hyam",
        "R. Stewart"
    ],
    "POR": [
        "Diogo Costa",
        "João Cancelo",
        "Rúben Dias",
        "Renato Veiga",
        "Nuno Mendes",
        "João Neves",
        "Vitinha",
        "Pedro Neto",
        "Rafael Leão",
        "Bruno Fernandes",
        "Cristiano Ronaldo",
        "Gonçalo Ramos",
        "Guedes",
        "Rúben Neves",
        "Bernardo Silva",
        "Gonçalo Inácio",
        "Diogo Dalot",
        "Rui Silva",
        "João Félix",
        "Samú Costa",
        "Trincão",
        "Tomás Araújo",
        "Matheus Nunes",
        "Francisco Conceição",
        "Nélson Semedo",
        "José Sá"
    ],
    "URU": [
        "F. Muslera",
        "G. Varela",
        "S. Cáceres",
        "M. Olivera",
        "J. Sanabria",
        "M. Ugarte",
        "A. Canobbio",
        "R. Bentancur",
        "F. Valverde",
        "M. Araújo",
        "D. Núñez",
        "B. Rodríguez",
        "F. Viñas",
        "R. Zalazar",
        "N. De la Cruz",
        "J. Giménez",
        "M. Viña",
        "S. Rochet",
        "J. Piquerez",
        "R. Aguirre",
        "S. Bueno",
        "E. Martínez",
        "F. Pellistri",
        "S. Mele",
        "R. Araujo",
        "G. De Arrascaeta"
    ],
    "TUR": [
        "U. Çakır",
        "Z. Çelik",
        "O. Kabak",
        "A. Bardakcı",
        "O. Aydın",
        "S. Özcan",
        "O. Kökçü",
        "E. Elmalı",
        "A. Güler",
        "K. Yıldız",
        "B. Yılmaz",
        "K. Aktürkoğlu",
        "H. Çalhanoğlu",
        "C. Uzun",
        "F. Kadıoğlu",
        "M. Demiral",
        "Ç. Söyüncü",
        "A. Bayındır",
        "İ. Yüksek",
        "Y. Akgün",
        "M. Günok",
        "M. Müldür",
        "D. Gül",
        "İ. Kahveci",
        "S. Akaydin",
        "K. Ayhan"
    ],
    "ESP": [
        "Unai Simón",
        "Pedro Porro",
        "Pau Cubarsí",
        "A. Laporte",
        "Marc Cucurella",
        "Rodri",
        "Fabián Ruiz",
        "Lamine Yamal",
        "Álex Baena",
        "Dani Olmo",
        "Oyarzabal",
        "Nico Williams",
        "Ferran Torres",
        "Pedri",
        "Zubimendi",
        "Marcos Llorente",
        "Eric García",
        "David Raya",
        "Víctor Muñoz",
        "Mikel Merino",
        "Gavi",
        "Grimaldo",
        "Pubill",
        "Joan García",
        "Yeremy Pino",
        "Borja Iglesias"
    ],
    "GHA": [
        "L. Zigi",
        "M. Senaya",
        "D. Luckassen",
        "J. Opoku",
        "G. Mensah",
        "T. Partey",
        "C. Yirenkyi",
        "K. Sibo",
        "Iñaki Williams",
        "J. Ayew",
        "A. Semenyo",
        "P. Adu",
        "A. Fatawu",
        "E. Owusu",
        "C. Bonsu Baah",
        "A. Mumin",
        "R. Baba",
        "B. Asare",
        "E. Nuamah",
        "A. Seidu",
        "K. Sulemana",
        "K. Oppong",
        "B. Thomas-Asante",
        "A. Boakye",
        "J. Adjetey",
        "J. Anang"
    ],
    "PAR": [
        "O. Gill",
        "J. Cáceres",
        "G. Velázquez",
        "G. Gómez",
        "O. Alderete",
        "J. Alonso",
        "M. Almirón",
        "D. Gómez",
        "A. Cubas",
        "M. Galarza",
        "J. Enciso",
        "G. Ávalos",
        "Mauricio",
        "R. Sosa",
        "D. Bobadilla",
        "G. Caballero",
        "J. Canale",
        "G. Olveira",
        "A. Sanabria",
        "I. Pitta",
        "B. Ojeda",
        "A. Arce",
        "Kaku",
        "F. Balbuena",
        "A. Maidana",
        "R. Fernández"
    ],
    "CRO": [
        "D. Livaković",
        "J. Stanišić",
        "J. Šutalo",
        "M. Pongračić",
        "J. Gvardiol",
        "L. Modrić",
        "M. Kovačić",
        "M. Pašalić",
        "I. Perišić",
        "P. Sučić",
        "P. Musa",
        "T. Fruk",
        "A. Kramarić",
        "M. Pašalić",
        "K. Jakić",
        "L. Vušković",
        "M. Erlić",
        "D. Kotarski",
        "I. Matanović",
        "A. Budimir",
        "N. Moro",
        "L. Sučić",
        "D. Ćaleta-Car",
        "I. Pandur",
        "N. Vlašić",
        "M. Baturina"
    ],
    "USA": [
        "M. Freese",
        "S. Dest",
        "C. Richards",
        "T. Ream",
        "A. Robinson",
        "C. Pulisic",
        "W. McKennie",
        "T. Adams",
        "T. Weah",
        "M. Tillman",
        "F. Balogun",
        "B. Aaronson",
        "R. Pepi",
        "C. Roldan",
        "G. Reyna",
        "J. Scally",
        "M. McKenzie",
        "M. Turner",
        "H. Wright",
        "A. Trusty",
        "C. Brady",
        "M. Robinson",
        "A. Freeman",
        "S. Berhalter",
        "M. Arfsten",
        "A. Zendejas"
    ],
    "AUT": [
        "A. Schlager",
        "S. Posch",
        "K. Danso",
        "D. Alaba",
        "K. Laimer",
        "N. Seiwald",
        "X. Schlager",
        "R. Schmid",
        "P. Wanner",
        "M. Sabitzer",
        "M. Gregoritsch",
        "M. Arnautović",
        "C. Chukwuemeka",
        "P. Wimmer",
        "F. Grillitsch",
        "P. Lienhart",
        "P. Mwene",
        "P. Pentz",
        "M. Friedl",
        "A. Prass",
        "F. Wiegele",
        "D. Affengruber",
        "M. Svoboda",
        "A. Schöpf",
        "S. Kalajdžić",
        "D. Ljubičić"
    ],
    "GER": [
        "M. Neuer",
        "J. Kimmich",
        "J. Tah",
        "A. Rüdiger",
        "N. Brown",
        "F. Nmecha",
        "A. Pavlović",
        "L. Sané",
        "F. Wirtz",
        "D. Undav",
        "K. Havertz",
        "J. Musiala",
        "A. Stiller",
        "L. Goretzka",
        "W. Anton",
        "D. Raum",
        "M. Thiaw",
        "O. Baumann",
        "N. Woltemade",
        "N. Amiri",
        "A. Ouédraogo",
        "M. Beier",
        "J. Leweling",
        "P. Groß",
        "A. Nübel",
        "N. Schlotterbeck"
    ],
    "COL": [
        "C. Vargas",
        "D. Muñoz",
        "D. Sánchez",
        "J. Lucumí",
        "J. Mojica",
        "G. Puerta",
        "J. Lerma",
        "J. Arias",
        "L. Díaz",
        "J. Rodríguez",
        "L. Suárez",
        "J. Córdoba",
        "J. Carrascal",
        "R. Ríos",
        "K. Castaño",
        "Y. Mina",
        "S. Arias",
        "Á. Montero",
        "J. Campaz",
        "D. Machado",
        "J. Quintero",
        "A. Gómez",
        "D. Ospina",
        "W. Ditta",
        "J. Portilla",
        "Cucho Hernández"
    ],
    "SWE": [
        "K. Nordfeldt",
        "G. Lagerbielke",
        "V. Lindelöf",
        "G. Gudmundsson",
        "J. Karlström",
        "A. Bernhardsson",
        "B. Nygren",
        "Y. Ayari",
        "E. Stroud",
        "V. Gyökeres",
        "A. Isak",
        "L. Bergvall",
        "M. Svanberg",
        "B. Zeneli",
        "T. Ali",
        "D. Svensson",
        "H. Ekdal",
        "V. Johansson",
        "A. Elanga",
        "G. Nilsson",
        "J. Widell Zetterström",
        "E. Smith",
        "I. Hien",
        "H. Johansson",
        "C. Starfelt",
        "K. Sema"
    ],
    "FRA": [
        "M. Maignan",
        "J. Koundé",
        "D. Upamecano",
        "W. Saliba",
        "L. Digne",
        "A. Tchouaméni",
        "A. Rabiot",
        "M. Olise",
        "O. Dembélé",
        "K. Mbappé",
        "B. Barcola",
        "D. Doué",
        "M. Thuram",
        "R. Cherki",
        "K. Koné",
        "T. Hernández",
        "M. Lacroix",
        "B. Samba",
        "W. Zaïre-Emery",
        "M. Gusto",
        "R. Risser",
        "M. Akliouche",
        "I. Konaté",
        "J. Mateta",
        "L. Hernández",
        "N. Kanté"
    ],
    "ECU": [
        "H. Galíndez",
        "A. Franco",
        "J. Ordoñez",
        "W. Pacho",
        "P. Hincapié",
        "J. Yeboah",
        "M. Caicedo",
        "P. Vite",
        "N. Angulo",
        "G. Plata",
        "E. Valencia",
        "Á. Preciado",
        "K. Páez",
        "J. Alcívar",
        "P. Estupiñán",
        "F. Torres",
        "Y. Medina",
        "G. Valle",
        "J. Porozo",
        "K. Rodríguez",
        "A. Minda",
        "D. Castillo",
        "M. Ramírez",
        "A. Valencia",
        "Jeremy",
        "J. Caicedo"
    ],
    "JPN": [
        "Z. Suzuki",
        "T. Watanabe",
        "H. Ito",
        "K. Itakura",
        "R. Doan",
        "D. Kamada",
        "K. Sano",
        "K. Nakamura",
        "T. Kubo",
        "A. Ueda",
        "J. Ito",
        "D. Maeda",
        "S. Machino",
        "A. Tanaka",
        "T. Tomiyasu",
        "Y. Sugawara",
        "S. Taniguchi",
        "T. Hayakawa",
        "Y. Suzuki",
        "A. Seko",
        "K. Goto",
        "J. Suzuki",
        "K. Ogawa",
        "Y. Nagatomo",
        "K. Shiogai",
        "K. Osako"
    ],
    "SEN": [
        "É. Mendy",
        "K. Diatta",
        "K. Koulibaly",
        "M. Niakhaté",
        "I. Jakobs",
        "I. Gueye",
        "P. Gueye",
        "I. Sarr",
        "S. Mané",
        "H. Diarra",
        "N. Jackson",
        "B. Dieng",
        "I. Ndiaye",
        "P. Sarr",
        "L. Camara",
        "E. Diouf",
        "M. Sarr",
        "M. Diaw",
        "A. Mendy",
        "A. Diao",
        "Y. Diouf",
        "A. Seck",
        "B. Sapoko Ndiaye",
        "P. Ciss",
        "I. Mbaye",
        "C. Ndiaye"
    ],
    "NED": [
        "B. Verbruggen",
        "D. Dumfries",
        "J. van Hecke",
        "V. van Dijk",
        "M. van de Ven",
        "R. Gravenberch",
        "F. de Jong",
        "T. Reijnders",
        "D. Malen",
        "B. Brobbey",
        "C. Gakpo",
        "M. de Roon",
        "T. Koopmeiners",
        "C. Summerville",
        "G. Til",
        "N. Aké",
        "L. Geertruida",
        "R. Roefs",
        "J. Kluivert",
        "M. Depay",
        "Q. Timber",
        "N. Lang",
        "M. Flekken",
        "J. Hato",
        "M. Wieffer",
        "W. Weghorst"
    ],
    "ENG": [
        "J. Pickford",
        "R. James",
        "E. Konsa",
        "M. Guéhi",
        "D. Spence",
        "E. Anderson",
        "J. Bellingham",
        "D. Rice",
        "B. Saka",
        "H. Kane",
        "A. Gordon",
        "O. Watkins",
        "N. Madueke",
        "E. Eze",
        "M. Rogers",
        "J. Stones",
        "N. O'Reilly",
        "D. Henderson",
        "M. Rashford",
        "D. Burn",
        "J. Quansah",
        "I. Toney",
        "T. Chalobah",
        "K. Mainoo",
        "J. Trafford",
        "J. Henderson"
    ],
    "BEL": [
        "T. Courtois",
        "T. Meunier",
        "A. Theate",
        "B. Mechele",
        "M. De Cuyper",
        "H. Vanaken",
        "Y. Tielemans",
        "A. Saelemaekers",
        "L. Trossard",
        "K. De Bruyne",
        "R. Lukaku",
        "J. Doku",
        "D. Lukébakio",
        "N. Raskin",
        "M. Fernandez-Pardo",
        "N. Ngoy",
        "K. De Winter",
        "S. Lammens",
        "T. Castagne",
        "Z. Debast",
        "A. Witsel",
        "J. Seys",
        "M. Penders",
        "Diego Moreira",
        "C. De Ketelaere",
        "A. Onana"
    ],
    "CUW": [
        "T. Rafaela",
        "J. Albertus",
        "K. Martis",
        "R. Alexander",
        "R. Heimers",
        "R. van Rooi",
        "J. Anastatia",
        "G. Manuel",
        "L. Macks",
        "D. Nigellus",
        "R. Rosamaria",
        "C. Merencia",
        "L. Bernardina",
        "D. Scholten",
        "R. Fabricia",
        "E. Henriquez",
        "J. Amelia",
        "R. Eustacia",
        "R. Schoop",
        "S. Apolonia",
        "J. Croes",
        "C. de Ridder",
        "E. Meulens",
        "Q. Josephia",
        "C. Andreia",
        "J. Jansen"
    ],
    "CIV": [
        "Y. Fofana",
        "W. Singo",
        "O. Kossounou",
        "E. Agbadou",
        "G. Konan",
        "I. Sangaré",
        "N. Pépé",
        "F. Kessié",
        "C. Inao Oulaï",
        "Y. Diomande",
        "Y. Bonny",
        "E. Guessand",
        "Amad",
        "B. Touré",
        "J. Seri",
        "O. Diomande",
        "G. Doué",
        "A. Lafont",
        "E. Ndicka",
        "O. Diakité",
        "M. Koné",
        "C. Operi",
        "S. Fofana",
        "P. Guiagon",
        "S. Adingra",
        "E. Wahi"
    ]
}
def initialize_scorers_state():
    """Inicializa el estado de goleadores."""
    return {
        "scorers": []  # Lista de goles: [{"match_id": int, "team": str, "player": str, "minute": int}, ...]
    }

def add_goal(scorers_state, match_id, team, player, minute):
    """Añade un gol al registro."""
    scorers_state["scorers"].append({
        "match_id": match_id,
        "team": team,
        "player": player,
        "minute": minute
    })
    return scorers_state

def get_top_scorers(scorers_state):
    """Retorna los máximos goleadores ordenados por cantidad de goles."""
    scorer_stats = {}
    for goal in scorers_state["scorers"]:
        player = goal["player"]
        team = goal["team"]
        if player not in scorer_stats:
            scorer_stats[player] = {"team": team, "goals": 0}
        scorer_stats[player]["goals"] += 1
    
    sorted_scorers = sorted(scorer_stats.items(), key=lambda x: x[1]["goals"], reverse=True)
    return sorted_scorers
