# -*- coding: utf-8 -*-
"""
teams_data.py
Datos de las 32 selecciones de FMMJ WORLD CUP UNITED 26: grupos, presidentes,
colores de anfitriones y convocatoria de 26 jugadores por selección.

Los 26 convocados de cada selección son jugadores reales (futbolistas que
existen y son elegibles por esa nacionalidad, en línea con lo que encontrarías
en la base de datos de sofifa.com para FC 26). No se pudo hacer scraping
automático y literal de sofifa.com porque el sitio bloquea el acceso de bots,
así que la lista se armó "a mano" combinando conocimiento futbolístico
actualizado; puede haber algún jugador que ya no esté convocado o que haya
cambiado de posición exacta en el juego. Si alguna selección necesita un
ajuste puntual, se puede corregir jugador por jugador sin tocar el resto.

100% autocontenido (no depende de ningún archivo externo ni de generación
aleatoria), para evitar problemas de despliegue en Streamlit Cloud / GitHub.
"""

GROUPS = {
    "A": [
        {"code": "MEX", "name": "México", "flag": "🇲🇽", "president": "Mati"},
        {"code": "KOR", "name": "Corea del Sur", "flag": "🇰🇷", "president": "Jnka"},
        {"code": "UKR", "name": "Ucrania", "flag": "🇺🇦", "president": "Dibu"},
        {"code": "NOR", "name": "Noruega", "flag": "🇳🇴", "president": "Mati"},
    ],
    "B": [
        {"code": "CAN", "name": "Canadá", "flag": "🇨🇦", "president": "Jnka"},
        {"code": "SUI", "name": "Suiza", "flag": "🇨🇭", "president": "Dibu"},
        {"code": "ITA", "name": "Italia", "flag": "🇮🇹", "president": "Jnka"},
        {"code": "ARG", "name": "Argentina", "flag": "🇦🇷", "president": "Mati"},
    ],
    "C": [
        {"code": "BRA", "name": "Brasil", "flag": "🇧🇷", "president": "Jnka"},
        {"code": "MAR", "name": "Marruecos", "flag": "🇲🇦", "president": "Mati"},
        {"code": "SCO", "name": "Escocia", "flag": "🇬🇧", "president": "Dibu"},
        {"code": "POR", "name": "Portugal", "flag": "🇵🇹", "president": "Dibu"},
    ],
    "D": [
        {"code": "USA", "name": "Estados Unidos", "flag": "🇺🇸", "president": "Mati"},
        {"code": "PAR", "name": "Paraguay", "flag": "🇵🇾", "president": "Dibu"},
        {"code": "TUR", "name": "Turquía", "flag": "🇹🇷", "president": "Mati"},
        {"code": "ENG", "name": "Inglaterra", "flag": "🇬🇧", "president": "Jnka"},
    ],
    "E": [
        {"code": "GER", "name": "Alemania", "flag": "🇩🇪", "president": "Jnka"},
        {"code": "AUT", "name": "Austria", "flag": "🇦🇹", "president": "Mati"},
        {"code": "ECU", "name": "Ecuador", "flag": "🇪🇨", "president": "Dibu"},
        {"code": "CUW", "name": "Curazao", "flag": "🇨🇼", "president": "Dibu"},
    ],
    "F": [
        {"code": "NED", "name": "Países Bajos", "flag": "🇳🇱", "president": "Mati"},
        {"code": "JPN", "name": "Japón", "flag": "🇯🇵", "president": "Jnka"},
        {"code": "SWE", "name": "Suecia", "flag": "🇸🇪", "president": "Dibu"},
        {"code": "SEN", "name": "Senegal", "flag": "🇸🇳", "president": "Jnka"},
    ],
    "G": [
        {"code": "BEL", "name": "Bélgica", "flag": "🇧🇪", "president": "Dibu"},
        {"code": "COL", "name": "Colombia", "flag": "🇨🇴", "president": "Jnka"},
        {"code": "CRO", "name": "Croacia", "flag": "🇭🇷", "president": "Mati"},
        {"code": "CIV", "name": "Costa de Marfil", "flag": "🇨🇮", "president": "Mati"},
    ],
    "H": [
        {"code": "ESP", "name": "España", "flag": "🇪🇸", "president": "Mati"},
        {"code": "URU", "name": "Uruguay", "flag": "🇺🇾", "president": "Jnka"},
        {"code": "GHA", "name": "Ghana", "flag": "🇬🇭", "president": "Dibu"},
        {"code": "FRA", "name": "Francia", "flag": "🇫🇷", "president": "Dibu"},
    ],
}

HOSTS = {
    "MEX": {"color": "#006341", "name": "México"},   # verde
    "USA": {"color": "#0A3161", "name": "Estados Unidos"},  # azul
    "CAN": {"color": "#D80621", "name": "Canadá"},   # rojo
}

SQUADS = {
    "MEX": [
        {"dorsal": 1, "nombre": "Luis Malagón", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Guillermo Ochoa", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Carlos Acevedo", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Julián Araujo", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Jesús Gallardo", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "César Montes", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Johan Vásquez", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Gerardo Arteaga", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Kevin Álvarez", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Jorge Sánchez", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Israel Reyes", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Edson Álvarez", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Luis Chávez", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Orbelín Pineda", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Erick Sánchez", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Carlos Rodríguez", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Marcel Ruiz", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Fidel Ambriz", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Diego Lainez", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Santiago Giménez", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Raúl Jiménez", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Hirving Lozano", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Uriel Antuna", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Alexis Vega", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Julián Quiñones", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "César Huerta", "posicion": "DEL"},
    ],
    "KOR": [
        {"dorsal": 1, "nombre": "Jo Hyeon-woo", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Kim Seung-gyu", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Song Bum-keun", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Kim Min-jae", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Kim Young-gwon", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Kim Ju-sung", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Seol Young-woo", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Kim Tae-hwan", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Lee Ki-je", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Park Jin-seob", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Yoon Jong-gyu", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Hwang In-beom", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Park Yong-woo", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Baek Seung-ho", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Lee Jae-sung", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Jung Woo-young", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Hong Hyun-seok", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Moon Seon-min", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Lee Soon-min", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Son Heung-min", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Cho Gue-sung", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Hwang Hee-chan", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Oh Hyeon-gyu", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Um Won-sang", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Lee Dong-jun", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Yang Min-hyeok", "posicion": "DEL"},
    ],
    "UKR": [
        {"dorsal": 1, "nombre": "Anatoliy Trubin", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Georgiy Bushchan", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Andriy Lunin", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Illia Zabarnyi", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Oleksandr Svatok", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Vitaliy Mykolenko", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Yukhym Konoplia", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Valeriy Bondar", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Oleksandr Tymchyk", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Denys Popov", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Bogdan Mykhaylichenko", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Mykola Shaparenko", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Georgiy Sudakov", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Taras Stepanenko", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Oleksandr Zubkov", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Ruslan Malinovskyi", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Viktor Tsyhankov", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Illia Vitor", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Volodymyr Brazhko", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Artem Dovbyk", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Roman Yaremchuk", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Mykhailo Mudryk", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Vladyslav Vanat", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Danylo Sikan", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Vladyslav Supryaga", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Artem Bondarenko", "posicion": "DEL"},
    ],
    "NOR": [
        {"dorsal": 1, "nombre": "Ørjan Nyland", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Kristoffer Klaesson", "posicion": "POR"},
        {"dorsal": 3, "nombre": "André Hansen", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Leo Østigård", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "David Møller Wolfe", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Julian Ryerson", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Birger Meling", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Stefan Strandberg", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Fredrik Bjørkan", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Andreas Hanche-Olsen", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Marcus Pedersen", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Martin Ødegaard", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Sander Berge", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Morten Thorsby", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Kristian Thorstvedt", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Fredrik Aursnes", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Mathias Normann", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Patrick Berg", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Ola Solbakken", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Erling Haaland", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Alexander Sørloth", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Antonio Nusa", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Oscar Bobb", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Jens Petter Hauge", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Bård Finne", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Ohi Omoijuanfo", "posicion": "DEL"},
    ],
    "CAN": [
        {"dorsal": 1, "nombre": "Maxime Crépeau", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Dayne St. Clair", "posicion": "POR"},
        {"dorsal": 3, "nombre": "James Pantemis", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Alphonso Davies", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Moise Bombito", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Kamal Miller", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Alistair Johnston", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Derek Cornelius", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Richie Laryea", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Joel Waterman", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Sam Adekugbe", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Stephen Eustaquio", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Ismaël Koné", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Samuel Piette", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Mark-Anthony Kaye", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Jonathan Osorio", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Russell Teibert", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Ali Ahmed", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Jayden Nelson", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Jonathan David", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Cyle Larin", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Tajon Buchanan", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Jacob Shaffelburg", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Ike Ugbo", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Promise David", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Liam Millar", "posicion": "DEL"},
    ],
    "SUI": [
        {"dorsal": 1, "nombre": "Yann Sommer", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Gregor Kobel", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Philipp Köhn", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Manuel Akanji", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Nico Elvedi", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Ricardo Rodríguez", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Silvan Widmer", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Fabian Schär", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Cédric Zesiger", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Eray Cömert", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Loris Benito", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Granit Xhaka", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Remo Freuler", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Fabian Rieder", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Djibril Sow", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Xherdan Shaqiri", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Michel Aebischer", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Ardon Jashari", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Vincent Sierro", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Breel Embolo", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Zeki Amdouni", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Dan Ndoye", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Ruben Vargas", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Noah Okafor", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Steven Zuber", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Kwadwo Duah", "posicion": "DEL"},
    ],
    "ITA": [
        {"dorsal": 1, "nombre": "Gianluigi Donnarumma", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Alex Meret", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Guglielmo Vicario", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Alessandro Bastoni", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Giovanni Di Lorenzo", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Riccardo Calafiori", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Federico Dimarco", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Alessandro Buongiorno", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Gianluca Mancini", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Matteo Darmian", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Destiny Udogie", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Nicolò Barella", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Sandro Tonali", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Davide Frattesi", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Jorginho", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Lorenzo Pellegrini", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Nicolò Fagioli", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Michael Folorunsho", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Samuele Ricci", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Moise Kean", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Mateo Retegui", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Giacomo Raspadori", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Federico Chiesa", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Gianluca Scamacca", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Matteo Politano", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Nicolò Zaniolo", "posicion": "DEL"},
    ],
    "ARG": [
        {"dorsal": 1, "nombre": "Emiliano Martínez", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Gerónimo Rulli", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Walter Benítez", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Cristian Romero", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Nicolás Otamendi", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Nahuel Molina", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Lisandro Martínez", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Nicolás Tagliafico", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Gonzalo Montiel", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Marcos Acuña", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Facundo Medina", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Rodrigo De Paul", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Enzo Fernández", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Alexis Mac Allister", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Leandro Paredes", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Giovani Lo Celso", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Exequiel Palacios", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Thiago Almada", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Nicolás Paz", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Lionel Messi", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Julián Álvarez", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Lautaro Martínez", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Nicolás González", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Paulo Dybala", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Alejandro Garnacho", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Giuliano Simeone", "posicion": "DEL"},
    ],
    "BRA": [
        {"dorsal": 1, "nombre": "Alisson", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Ederson", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Bento", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Marquinhos", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Éder Militão", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Danilo", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Alex Sandro", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Wendell", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Gabriel Magalhães", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Vanderson", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Guilherme Arana", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Bruno Guimarães", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Casemiro", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Lucas Paquetá", "posicion": "MED"},
        {"dorsal": 15, "nombre": "João Gomes", "posicion": "MED"},
        {"dorsal": 16, "nombre": "André", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Andreas Pereira", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Douglas Luiz", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Fabinho", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Vinícius Júnior", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Rodrygo", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Raphinha", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Endrick", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Gabriel Martinelli", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Richarlison", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Matheus Cunha", "posicion": "DEL"},
    ],
    "MAR": [
        {"dorsal": 1, "nombre": "Yassine Bounou", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Munir Mohamedi", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Anas Zniti", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Achraf Hakimi", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Noussair Mazraoui", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Romain Saïss", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Nayef Aguerd", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Yahya Attiat-Allah", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Jawad El Yamiq", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Achraf Dari", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Adam Masina", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Sofyan Amrabat", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Azzedine Ounahi", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Selim Amallah", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Bilal El Khannouss", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Ilias Akhomach", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Amine Adli", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Yahya Jabrane", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Abdelhamid Sabiri", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Youssef En-Nesyri", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Hakim Ziyech", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Abde Ezzalzouli", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Ayoub El Kaabi", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Zakaria Aboukhlal", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Soufiane Rahimi", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Walid Cheddira", "posicion": "DEL"},
    ],
    "SCO": [
        {"dorsal": 1, "nombre": "Angus Gunn", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Robby McCrorie", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Zander Clark", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Andrew Robertson", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Kieran Tierney", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Scott McKenna", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Grant Hanley", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Jack Hendry", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Ryan Porteous", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Anthony Ralston", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Greg Taylor", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Scott McTominay", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Billy Gilmour", "posicion": "MED"},
        {"dorsal": 14, "nombre": "John McGinn", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Callum McGregor", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Ryan Christie", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Stuart Armstrong", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Kenny McLean", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Lewis Ferguson", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Che Adams", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Lyndon Dykes", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Ben Doak", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Tommy Conway", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "James Forrest", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Fraser Hornby", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Oli McBurnie", "posicion": "DEL"},
    ],
    "POR": [
        {"dorsal": 1, "nombre": "Diogo Costa", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Rui Patrício", "posicion": "POR"},
        {"dorsal": 3, "nombre": "José Sá", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Rúben Dias", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "António Silva", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Nuno Mendes", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Diogo Dalot", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Gonçalo Inácio", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Nélson Semedo", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Danilo Pereira", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "João Cancelo", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Bruno Fernandes", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Vitinha", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Bernardo Silva", "posicion": "MED"},
        {"dorsal": 15, "nombre": "João Neves", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Rúben Neves", "posicion": "MED"},
        {"dorsal": 17, "nombre": "William Carvalho", "posicion": "MED"},
        {"dorsal": 18, "nombre": "João Palhinha", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Pedro Neto", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Cristiano Ronaldo", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Rafael Leão", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Gonçalo Ramos", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Diogo Jota", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "João Félix", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Francisco Conceição", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Fábio Silva", "posicion": "DEL"},
    ],
    "USA": [
        {"dorsal": 1, "nombre": "Matt Turner", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Ethan Horvath", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Patrick Schulte", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Sergiño Dest", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Antonee Robinson", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Chris Richards", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Tim Ream", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Miles Robinson", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Joe Scally", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Cameron Carter-Vickers", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Mark McKenzie", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Weston McKennie", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Tyler Adams", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Yunus Musah", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Luca de la Torre", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Gianluca Busio", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Johnny Cardoso", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Malik Tillman", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Brenden Aaronson", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Christian Pulisic", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Folarin Balogun", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Ricardo Pepi", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Timothy Weah", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Josh Sargent", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Giovanni Reyna", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Haji Wright", "posicion": "DEL"},
    ],
    "PAR": [
        {"dorsal": 1, "nombre": "Roberto Fernández", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Antony Silva", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Carlos Coronel", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Gustavo Gómez", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Omar Alderete", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Alberto Espínola", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Fabián Balbuena", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Iván Franco", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Robert Rojas", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Blas Riveros", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Junior Alonso", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Mathías Villasanti", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Andrés Cubas", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Diego Gómez", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Damián Bobadilla", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Julio Enciso", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Ramón Sosa", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Braian Samudio", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Ángel Cardozo Lucena", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Antonio Sanabria", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Adam Bareiro", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Miguel Almirón", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Ronaldo Martínez", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Derlis González", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Federico Santander", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Alejandro Romero Gamarra", "posicion": "DEL"},
    ],
    "TUR": [
        {"dorsal": 1, "nombre": "Uğurcan Çakır", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Altay Bayındır", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Mert Günok", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Merih Demiral", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Zeki Çelik", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Kaan Ayhan", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Ferdi Kadıoğlu", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Abdülkerim Bardakcı", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Samet Akaydin", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Ridvan Yılmaz", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Mert Müldür", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Hakan Çalhanoğlu", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Orkun Kökçü", "posicion": "MED"},
        {"dorsal": 14, "nombre": "İsmail Yüksek", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Salih Özcan", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Arda Güler", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Yunus Akgün", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Kenan Yıldız", "posicion": "MED"},
        {"dorsal": 19, "nombre": "İrfan Can Kahveci", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Barış Alper Yılmaz", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Cengiz Ünder", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Kerem Aktürkoğlu", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Halil Dervişoğlu", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Enes Ünal", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Yusuf Yazıcı", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Bertuğ Yıldırım", "posicion": "DEL"},
    ],
    "ENG": [
        {"dorsal": 1, "nombre": "Jordan Pickford", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Aaron Ramsdale", "posicion": "POR"},
        {"dorsal": 3, "nombre": "James Trafford", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Kyle Walker", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "John Stones", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Marc Guéhi", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Levi Colwill", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Ezri Konsa", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Kieran Trippier", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Reece James", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Trent Alexander-Arnold", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Declan Rice", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Jude Bellingham", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Conor Gallagher", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Kobbie Mainoo", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Adam Wharton", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Jordan Henderson", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Curtis Jones", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Cole Palmer", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Harry Kane", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Bukayo Saka", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Phil Foden", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Ollie Watkins", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Anthony Gordon", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Marcus Rashford", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Eberechi Eze", "posicion": "DEL"},
    ],
    "GER": [
        {"dorsal": 1, "nombre": "Manuel Neuer", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Marc-André ter Stegen", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Oliver Baumann", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Antonio Rüdiger", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Jonathan Tah", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Nico Schlotterbeck", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "David Raum", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Benjamin Henrichs", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Waldemar Anton", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Maximilian Mittelstädt", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Robin Koch", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Joshua Kimmich", "posicion": "MED"},
        {"dorsal": 13, "nombre": "İlkay Gündoğan", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Robert Andrich", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Pascal Groß", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Jamal Musiala", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Florian Wirtz", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Chris Führich", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Aleksandar Pavlović", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Kai Havertz", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Niclas Füllkrug", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Leroy Sané", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Deniz Undav", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Serge Gnabry", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Karim Adeyemi", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Maximilian Beier", "posicion": "DEL"},
    ],
    "AUT": [
        {"dorsal": 1, "nombre": "Patrick Pentz", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Alexander Schlager", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Heinz Lindner", "posicion": "POR"},
        {"dorsal": 4, "nombre": "David Alaba", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Kevin Danso", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Philipp Lienhart", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Stefan Posch", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Alexander Prass", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Maximilian Wöber", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Gernot Trauner", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Phillipp Mwene", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Marcel Sabitzer", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Konrad Laimer", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Christoph Baumgartner", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Nicolas Seiwald", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Florian Grillitsch", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Xaver Schlager", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Romano Schmid", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Patrick Wimmer", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Marko Arnautović", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Michael Gregoritsch", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Sasa Kalajdzic", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Karim Onisiwo", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Marco Grüll", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Junior Adamu", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Andreas Weimann", "posicion": "DEL"},
    ],
    "ECU": [
        {"dorsal": 1, "nombre": "Hernán Galíndez", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Moisés Ramírez", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Alexander Domínguez", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Piero Hincapié", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Félix Torres", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "William Pacho", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Ángelo Preciado", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Pervis Estupiñán", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Jackson Porozo", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Diego Palacios", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Xavier Arreaga", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Moisés Caicedo", "posicion": "MED"},
        {"dorsal": 13, "nombre": "José Cifuentes", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Alan Franco", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Jhegson Méndez", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Kendry Páez", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Carlos Gruezo", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Jeremy Sarmiento", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Romario Ibarra", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Enner Valencia", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Kevin Rodríguez", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Gonzalo Plata", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Ángel Mena", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Leonardo Campana", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Michael Estrada", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Jordy Caicedo", "posicion": "DEL"},
    ],
    "CUW": [
        {"dorsal": 1, "nombre": "Eloy Room", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Shanon Cijntje", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Shendrick Luidens", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Cuco Martina", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Sherel Floranus", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Ulrick Eugene", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Elscott Balentin", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Jean-Luc Leefdael", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Chris Kalis", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Ivar Israel", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Jurich Carolina", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Juninho Bacuna", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Leandro Bacuna", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Tahith Chong", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Dabney dos Santos", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Enric Llansana", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Jeremy Antonisse", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Kenji Gorré", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Roly Bonevacia", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Rangelo Janga", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Charlison Benschop", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Gino van Kessel", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Elson Hooi", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Silvano Comvalius", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Jurgen Locadia", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Danzell Gravenberch", "posicion": "DEL"},
    ],
    "NED": [
        {"dorsal": 1, "nombre": "Bart Verbruggen", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Justin Bijlow", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Mark Flekken", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Virgil van Dijk", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Jurrien Timber", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Nathan Aké", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Micky van de Ven", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Denzel Dumfries", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Ian Maatsen", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Jeremie Frimpong", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Stefan de Vrij", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Frenkie de Jong", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Tijjani Reijnders", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Xavi Simons", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Ryan Gravenberch", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Teun Koopmeiners", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Joey Veerman", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Marten de Roon", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Jerdy Schouten", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Memphis Depay", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Cody Gakpo", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Wout Weghorst", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Donyell Malen", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Steven Bergwijn", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Brian Brobbey", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Joshua Zirkzee", "posicion": "DEL"},
    ],
    "JPN": [
        {"dorsal": 1, "nombre": "Zion Suzuki", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Keisuke Osako", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Shuichi Gonda", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Takehiro Tomiyasu", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Ko Itakura", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Hiroki Ito", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Yukinari Sugawara", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Shogo Taniguchi", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Miki Yamane", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Daiki Hashioka", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Yuto Nagatomo", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Wataru Endo", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Hidemasa Morita", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Ao Tanaka", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Takefusa Kubo", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Kaoru Mitoma", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Ritsu Doan", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Junya Ito", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Daichi Kamada", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Ayase Ueda", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Takuma Asano", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Koki Ogawa", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Shuto Machino", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Yuki Soma", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Kyogo Furuhashi", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Kaishu Sano", "posicion": "DEL"},
    ],
    "SWE": [
        {"dorsal": 1, "nombre": "Robin Olsen", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Kristoffer Nordfeldt", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Viktor Johansson", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Victor Lindelöf", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Isak Hien", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Emil Krafth", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Ludwig Augustinsson", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Filip Helander", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Carl Starfelt", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Pierre Bengtsson", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Jonathan Levi", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Sead Haksabanovic", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Jesper Karlström", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Kristoffer Olsson", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Hugo Larsson", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Yasin Ayari", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Anton Salétros", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Albin Ekdal", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Ken Sema", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Alexander Isak", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Viktor Gyökeres", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Anthony Elanga", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Gustav Isaksen", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Dejan Kulusevski", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Jesper Karlsson", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Emil Forsberg", "posicion": "DEL"},
    ],
    "SEN": [
        {"dorsal": 1, "nombre": "Édouard Mendy", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Seny Dieng", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Alfred Gomis", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Kalidou Koulibaly", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Abdou Diallo", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Ismail Jakobs", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Youssouf Sabaly", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Formose Mendy", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Moussa Niakhaté", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Fodé Ballo-Touré", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Pape Abou Cissé", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Idrissa Gueye", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Nampalys Mendy", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Pape Matar Sarr", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Krépin Diatta", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Iliman Ndiaye", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Cheikhou Kouyaté", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Pathé Ciss", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Pape Gueye", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Sadio Mané", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Boulaye Dia", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Habib Diallo", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Nicolas Jackson", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Ismaila Sarr", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Chérif Ndiaye", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Ibrahima Niane", "posicion": "DEL"},
    ],
    "BEL": [
        {"dorsal": 1, "nombre": "Koen Casteels", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Matz Sels", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Thomas Kaminski", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Wout Faes", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Jan Vertonghen", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Arthur Theate", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Zeno Debast", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Timothy Castagne", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Thomas Meunier", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Maxim De Cuyper", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Ameen Al-Dakhil", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Kevin De Bruyne", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Youri Tielemans", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Amadou Onana", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Arthur Vermeeren", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Orel Mangala", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Hans Vanaken", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Thorgan Hazard", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Mario Stroeykens", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Romelu Lukaku", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Jérémy Doku", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Leandro Trossard", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Loïs Openda", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Johan Bakayoko", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Charles De Ketelaere", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Dodi Lukebakio", "posicion": "DEL"},
    ],
    "COL": [
        {"dorsal": 1, "nombre": "Camilo Vargas", "posicion": "POR"},
        {"dorsal": 2, "nombre": "David Ospina", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Kevin Mier", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Davinson Sánchez", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Yerry Mina", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Jhon Lucumí", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Daniel Muñoz", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Johan Mojica", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "William Tesillo", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Santiago Arias", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Cristian Borja", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "James Rodríguez", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Jefferson Lerma", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Richard Ríos", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Kevin Castaño", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Mateus Uribe", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Jorge Carrascal", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Gustavo Puerta", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Éder Álvarez Balanta", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Luis Díaz", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Rafael Santos Borré", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Jhon Córdoba", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Jhon Durán", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Yaser Asprilla", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Miguel Borja", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Daniel Ruiz", "posicion": "DEL"},
    ],
    "CRO": [
        {"dorsal": 1, "nombre": "Dominik Livaković", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Nediljko Labrović", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Ivica Ivušić", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Josip Šutalo", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Joško Gvardiol", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Borna Sosa", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Josip Stanišić", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Domagoj Bradarić", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Martin Erlić", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Marin Pongračić", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Borna Barišić", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Luka Modrić", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Mateo Kovačić", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Marcelo Brozović", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Lovro Majer", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Nikola Vlašić", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Luka Sučić", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Kristijan Jakić", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Martin Baturina", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Andrej Kramarić", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Ante Budimir", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Bruno Petković", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Marko Pjaca", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Mario Pašalić", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Marko Livaja", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Ivan Perišić", "posicion": "DEL"},
    ],
    "CIV": [
        {"dorsal": 1, "nombre": "Yahia Fofana", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Badra Ali Sangaré", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Mohamed Koffi", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Odilon Kossounou", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Willy Boly", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Ghislain Konan", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Wilfried Singo", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Serge Aurier", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Evan Ndicka", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Eric Bailly", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Souleyman Doumbia", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Franck Kessié", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Seko Fofana", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Jean-Michel Seri", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Ibrahim Sangaré", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Hamed Traorè", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Christ Inao Oulaï", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Jérémie Boga", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Yohan Boli", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Sébastien Haller", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Nicolas Pépé", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Simon Adingra", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Wilfried Zaha", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Max-Alain Gradel", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Christian Kouamé", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Oumar Diakité", "posicion": "DEL"},
    ],
    "ESP": [
        {"dorsal": 1, "nombre": "Unai Simón", "posicion": "POR"},
        {"dorsal": 2, "nombre": "David Raya", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Álex Remiro", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Robin Le Normand", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Aymeric Laporte", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Dani Vivian", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Marc Cucurella", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Jesús Navas", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Pau Cubarsí", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Alejandro Grimaldo", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Dani Carvajal", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Rodri", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Fabián Ruiz", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Pedri", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Martín Zubimendi", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Mikel Merino", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Dani Olmo", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Fermín López", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Álex Baena", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Álvaro Morata", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Nico Williams", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Lamine Yamal", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Ferran Torres", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Mikel Oyarzabal", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Ayoze Pérez", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Borja Iglesias", "posicion": "DEL"},
    ],
    "URU": [
        {"dorsal": 1, "nombre": "Sergio Rochet", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Franco Israel", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Santiago Mele", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Ronald Araújo", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "José María Giménez", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Sebastián Cáceres", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Mathías Olivera", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Guillermo Varela", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Matías Viña", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Marcelo Saracchi", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Sebastián Coates", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Federico Valverde", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Manuel Ugarte", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Rodrigo Bentancur", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Giorgian de Arrascaeta", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Agustín Canobbio", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Nicolás de la Cruz", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Nahitan Nández", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Lucas Torreira", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Darwin Núñez", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Luis Suárez", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Facundo Torres", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Facundo Pellistri", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Maximiliano Araújo", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Cristhian Olivera", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Brian Rodríguez", "posicion": "DEL"},
    ],
    "GHA": [
        {"dorsal": 1, "nombre": "Lawrence Ati-Zigi", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Jojo Wollacott", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Danlad Ibrahim", "posicion": "POR"},
        {"dorsal": 4, "nombre": "Alexander Djiku", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Tariq Lamptey", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Gideon Mensah", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Denis Odoi", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Joseph Aidoo", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Jonathan Mensah", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Baba Rahman", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Alidu Seidu", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Thomas Partey", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Mohammed Kudus", "posicion": "MED"},
        {"dorsal": 14, "nombre": "Elisha Owusu", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Salis Abdul Samed", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Iddrisu Baba", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Majeed Ashimeru", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Andre Ayew", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Ernest Nuamah", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Jordan Ayew", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Antoine Semenyo", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Inaki Williams", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Abdul Fatawu Issahaku", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Kamaldeen Sulemana", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Osman Bukari", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Felix Afena-Gyan", "posicion": "DEL"},
    ],
    "FRA": [
        {"dorsal": 1, "nombre": "Mike Maignan", "posicion": "POR"},
        {"dorsal": 2, "nombre": "Brice Samba", "posicion": "POR"},
        {"dorsal": 3, "nombre": "Alphonse Areola", "posicion": "POR"},
        {"dorsal": 4, "nombre": "William Saliba", "posicion": "DEF"},
        {"dorsal": 5, "nombre": "Ibrahima Konaté", "posicion": "DEF"},
        {"dorsal": 6, "nombre": "Jules Koundé", "posicion": "DEF"},
        {"dorsal": 7, "nombre": "Theo Hernández", "posicion": "DEF"},
        {"dorsal": 8, "nombre": "Ferland Mendy", "posicion": "DEF"},
        {"dorsal": 9, "nombre": "Lucas Hernandez", "posicion": "DEF"},
        {"dorsal": 10, "nombre": "Benjamin Pavard", "posicion": "DEF"},
        {"dorsal": 11, "nombre": "Dayot Upamecano", "posicion": "DEF"},
        {"dorsal": 12, "nombre": "Aurélien Tchouaméni", "posicion": "MED"},
        {"dorsal": 13, "nombre": "Eduardo Camavinga", "posicion": "MED"},
        {"dorsal": 14, "nombre": "N'Golo Kanté", "posicion": "MED"},
        {"dorsal": 15, "nombre": "Adrien Rabiot", "posicion": "MED"},
        {"dorsal": 16, "nombre": "Youssouf Fofana", "posicion": "MED"},
        {"dorsal": 17, "nombre": "Warren Zaïre-Emery", "posicion": "MED"},
        {"dorsal": 18, "nombre": "Manu Koné", "posicion": "MED"},
        {"dorsal": 19, "nombre": "Christopher Nkunku", "posicion": "MED"},
        {"dorsal": 20, "nombre": "Kylian Mbappé", "posicion": "DEL"},
        {"dorsal": 21, "nombre": "Ousmane Dembélé", "posicion": "DEL"},
        {"dorsal": 22, "nombre": "Marcus Thuram", "posicion": "DEL"},
        {"dorsal": 23, "nombre": "Randal Kolo Muani", "posicion": "DEL"},
        {"dorsal": 24, "nombre": "Bradley Barcola", "posicion": "DEL"},
        {"dorsal": 25, "nombre": "Olivier Giroud", "posicion": "DEL"},
        {"dorsal": 26, "nombre": "Michael Olise", "posicion": "DEL"},
    ],
}
def _build_teams():
    teams = {}
    for group_letter, teamlist in GROUPS.items():
        for t in teamlist:
            teams[t["code"]] = {
                "code": t["code"],
                "name": t["name"],
                "flag": t["flag"],
                "president": t["president"],
                "group": group_letter,
                "is_host": t["code"] in HOSTS,
                "squad": SQUADS[t["code"]],
            }
    return teams


TEAMS = _build_teams()
